version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@1.0.4
  gcp-gae: circleci/gcp-gae@1.0.4

jobs:
  build_and_push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - setup_remote_docker
      - gcp-gcr/gcr-auth
      - run: docker build -t gcr.io/$GOOGLE_PROJECT_ID/latam-app:$CIRCLE_SHA1 .
      - gcp-gcr/push-image:
          image: gcr.io/$GOOGLE_PROJECT_ID/latam-app
          tag: $CIRCLE_SHA1

  deploy:
    executor: gcp-gae/default
    steps:
      - run:
          name: Deploy to Google Cloud Run
          command: |
            gcloud run deploy latam-app \
              --image gcr.io/$GOOGLE_PROJECT_ID/latam-app:$CIRCLE_SHA1 \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated

  integration_tests:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Integration and Unit Tests
          command: npm test

workflows:
  build_and_deploy:
    jobs:
      - build_and_push
      - deploy:
          requires:
            - build_and_push
      - integration_tests:
          requires:
            - deploy
