version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.3
  gcp-gcr: circleci/gcp-gcr@1.0.4

jobs:
  build_and_push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - gcp-gcr/gcr-auth:
          gcp-key: GCLOUD_SERVICE_KEY
      - run:
          name: Build and push Docker image
          command: |
            IMAGE_TAG=gcr.io/$GOOGLE_PROJECT_ID/latam-app:$CIRCLE_SHA1
            docker build -t $IMAGE_TAG .
            docker push $IMAGE_TAG

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - gcp-cli/install
      - gcp-cli/initialize-gcloud:
          gcp-key: GCLOUD_SERVICE_KEY
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy latam-app \
              --image gcr.io/$GOOGLE_PROJECT_ID/myapp:$CIRCLE_SHA1 \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated

workflows:
  build_and_deploy:
    jobs:
      - build_and_push
      - deploy:
          requires:
            - build_and_push
